### ISSUE TITLE
`--download-sections` unsupported

### ISSUE THREAD

**Issue by ekrata-main** [microlinkhq/youtube-dl-exec#195]
no downloadSections param available on options object

**Comment by Kikobeats** [comment]
The library goals was never to be useful for download, use the raw binary for that 🙂

**Comment by mikeyaworski** [comment]
I disagree with closing this issue.

1. `--download-sections` works as is because it is passed to yt-dlp, but it's just not included in the `Flags` type.
2. This flag is perfect for seeking to specific parts of the video, even when streaming the data from yt-dlp to whatever else. I'm not sure what downloading has to do with it. I use this flag for streaming audio to Discord.

**Comment by Kikobeats** [comment]
@mikeyaworski can you make a PR?
