### ISSUE TITLE
React-Native Compatibility

### ISSUE THREAD

**Issue by Marinos33** [microlinkhq/youtube-dl-exec#49]
Hi,

It's seems that this package is not compatible with React-Native because it uses some module from NodeJS that are not implemented in React-Native, the modules involved are: assert, child_process, fs, os, path, stream and util. I tried to implement them first with 
node-libs-react-native and then with rn-nodeify but I cannot make it works. 

Do you have any Idea how I could use this package in a React-Native app ?

Thanks in advance.

**Comment by Marinos33** [comment]
Firstly, thanks for the reply.

Then, the issue is that react-native implement Node.js indeed. But all modules of Node.js are not available or doesn't work in the same way as in pure Node.js, because react-native is more of a "browser" environment so they are not compiled in the same way. While it exists some libraries that adapt those APIs like "react-native-path" to replace the module "path" of Node.js, those packages are meant to be used directly in the code and not to replace the dependencies of other installed package because they wont have the same behavior. On top of that, the environment variable are not the same between React-Native and Node.js, for example the process.version doesn't no exist in react-native and some packages use it.

Technically, it should be possible to polyfill those ones but it will be a pain because you will have to polyfill a lot of APIs from Node.js and I tried to do it but it doesn't seems to work (or at least I cannot make it works). Or, I could rewrite your code with the APIs for React-Native but I don't have neither the time nor the will to do that 😅.

So it's seems that your package is more focused to be used in a backend environment.

**Comment by WillSmithTE** [comment]
Just chiming in here as someone else interested in using the library in a react-native app. There are plenty of youtube-downloaders for react-native, but none are as good as the real youtube-dl like this library

**Comment by Kikobeats** [comment]
This library is tiny because it's essentially spawning the `youtube-dl` command.

The `youtube-dl` is some code executed by `python`.

That is still "light" assuming you are running it in an environment where `python` is installed (like a server).

In the case of React Native, you should move all these layers to be executed inside the React Native host device (a phone instead of a server).

So even technically is possible it's too much hard work.  A good enough solution might be to have a microservice that does the thing.

I'm missing what you want to achieve in your React Native application, but in case you are interested in getting video information (like duration, size, format, etc)  you can use ping [Microlink API](https://microlink.io/docs/api/getting-started/overview) passing a video URL:

e.g.,  [api.microlink.io/?url=https://file-examples-com.github.io/uploads/2017/04/file_example_MP4_480_1_5MG.mp4&video](https://api.microlink.io/?url=https://file-examples-com.github.io/uploads/2017/04/file_example_MP4_480_1_5MG.mp4&video)

Otherwise, you can use this library for creating your own microservice 🙂
