### ISSUE TITLE
Merging Audio and Video

### ISSUE THREAD

**Issue by Samiul30** [microlinkhq/youtube-dl-exec#91]
How to get all videos with audio? That means I want to merge them together.

**Comment by Kikobeats** [comment]
Hello,

You should to learn [youtube-dl](https://github.com/ytdl-org/youtube-dl) arguments to use this library.

Otherwise, consider use [Microlink API](https://microlink.io/api) passing [`audio`](https://microlink.io/docs/api/parameters/audio) and [`video`](https://microlink.io/docs/api/parameters/video) query parameters:

e.g., https://api.microlink.io?url=https://www.youtube.com/watch?v=6xKWiCMKKJg&audio&video
